"""Build the public subconverter template and native local rule providers."""
from pathlib import Path
from generate_groups import build_groups
ROOT = Path(__file__).resolve().parents[1]
(ROOT/'config/groups.ini').write_text(build_groups())
header = "; Generated by scripts/build.py. Edit config/ and rules/local/.\n"
(ROOT/'Clash-Full.ini').write_text(header + '\n'.join((ROOT/'config'/n).read_text() for n in ['rules.ini','groups.ini','settings.ini']))
for source in sorted((ROOT/'rules/local').glob('*.list')):
    lines = [x.strip() for x in source.read_text().splitlines() if x.strip() and not x.lstrip().startswith('#')]
    if len(lines) != len(set(lines)) or any(len(x.split(',')) != 2 for x in lines):
        raise ValueError(f'{source.name}: duplicate rule or embedded policy')
    (ROOT/'rules/clash'/source.with_suffix('.yaml').name).write_text('# Generated from rules/local/'+source.name+'\npayload:\n'+''.join('  - '+repr(x)+'\n' for x in lines))
print('Built Clash-Full.ini and local rule providers')
