"""Generate compact service selectors and exclusive name-based region filters."""
from pathlib import Path
import json
import re
ROOT=Path(__file__).resolve().parents[1]

def settings():
    return json.loads((ROOT/'config/regions.json').read_text())

def services():
    return json.loads((ROOT/'config/services.json').read_text())

def service_names():
    return [s['name'] for s in services()]

def eligible_pattern():
    blocked='|'.join(re.escape(s) for s in settings()['exclude'])
    return '(?i)^(?!.*(?:'+blocked+')).+'

def marker(region):
    # ASCII boundaries allow .US中文 while excluding RUS and unrelated words.
    codes='|'.join(re.escape(s) for s in region['codes'])
    names='|'.join(re.escape(s) for s in region['names'])
    return '(?:(?<![A-Za-z])(?:'+codes+')(?![A-Za-z])|'+names+')'

def region_patterns():
    config=settings()
    regions=config['regions']
    guard=eligible_pattern()[:-2]  # remove .+, keep case flag/anchor/exclusion
    result={}
    for name,region in regions.items():
        own=marker(region)
        other='|'.join(marker(r) for n,r in regions.items() if n!=name)
        # The user clarified that XX🔛 is a forwarding label, not the
        # region to classify. Consume all such leading labels before matching.
        # The negative lookahead prevents backtracking into a consumed label.
        relay='(?:[A-Za-z]{2,3}🔛)*(?![A-Za-z]{2,3}🔛)'
        result[name]=guard+relay+'(?!.*(?:'+other+'))(?=.*'+own+').+$'
    return result

def build_groups():
    regions=region_patterns()
    choices=['DIRECT','所有-手动','所有-自动']+[n+'节点' for n in regions]+['REJECT']
    rows=['; Generated by scripts/generate_groups.py. Edit config/services.json and config/regions.json.',
          '; 服务只选组；地区节点默认自动，选择具体节点后固定，选回地区自动即可恢复。']
    for service in services():
        refs=list(dict.fromkeys([service['default'],*service['extra'],*choices]))
        rows.append('custom_proxy_group='+service['name']+'`select`'+'`'.join('[]'+r for r in refs))
    rows+=['','; 所有手动可选择有效节点，包括尚未识别地区的节点。',
           'custom_proxy_group=所有-手动`select`'+eligible_pattern()+'`[]REJECT',
           'custom_proxy_group=所有-自动`url-test`'+eligible_pattern()+'`[]REJECT`http://www.gstatic.com/generate_204`180,5,100',
           '', '; 地区选择卡片：默认进入同地区自动测速，也可手动固定节点。']
    for name,pattern in regions.items():
        rows.append('custom_proxy_group='+name+'节点`select`[]'+name+'-自动`'+pattern+'`[]REJECT')
    rows+=['','; 自动测速辅助组。日常在上面的地区节点卡片操作即可。']
    for name,pattern in regions.items():
        rows.append('custom_proxy_group='+name+'-自动`url-test`'+pattern+'`[]REJECT`http://www.gstatic.com/generate_204`180,5,100')
    return '\n'.join(rows)+'\n'

if __name__=='__main__':
    (ROOT/'config/groups.ini').write_text(build_groups())
