"""Refresh narrowly filtered upstream providers; never changes service policies."""
from pathlib import Path
import json
import urllib.request
import yaml

ROOT = Path(__file__).resolve().parents[1]
BM = 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/'
SOURCES = {
    'AppleServices': (BM+'Apple/Apple_Classical_No_Resolve.yaml', {'akadns.net'}, False),
    'MicrosoftServices': (BM+'Microsoft/Microsoft.yaml',
        {'b.akamaiedge.net', 'g.akamaiedge.net', 'edgesuite.net', 'akadns.net'}, False),
    'AmazonServices': (BM+'Amazon/Amazon_No_Resolve.yaml',
        {'amazonaws-china.com', 'amazonaws.co.uk', 'amazonaws.com',
         'amazonaws.com.cn', 'amazonaws.tv', 'cloudfront.net'}, True),
    'OtherAI': ('https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.yaml',
        {'turn.livekit.cloud', 'host.livekit.cloud', 'browser-intake-datadoghq.com',
         'gateway.ai.cloudflare.com'}, False),
}

def filter_rules(name, payload):
    _, excluded, remove_ip = SOURCES[name]
    output, removed = [], []
    for entry in payload:
        if not isinstance(entry, str): raise ValueError('Non-string upstream rule')
        if name == 'OtherAI':
            entry = ('DOMAIN-SUFFIX,'+entry[2:]) if entry.startswith('+.') else ('DOMAIN,'+entry)
        fields = entry.split(',')
        if len(fields) < 2 or fields[0] not in {'DOMAIN','DOMAIN-SUFFIX','DOMAIN-KEYWORD','IP-CIDR','IP-CIDR6','PROCESS-NAME'}:
            raise ValueError(f'Unsupported upstream rule: {entry}')
        if len(fields) != 2 and not (fields[0] in {'IP-CIDR','IP-CIDR6'} and len(fields) == 3 and fields[2] == 'no-resolve'):
            raise ValueError(f'Unexpected policy or options: {entry}')
        if fields[1] in excluded or (remove_ip and fields[0] in {'IP-CIDR','IP-CIDR6'}):
            removed.append(entry)
        elif entry not in output:
            output.append(entry)
    if not output: raise ValueError('Empty filtered provider')
    return output, removed

def main():
    pending, manifest = {}, {}
    previous_path = ROOT/'rules/filtered/manifest.json'
    previous = json.loads(previous_path.read_text()) if previous_path.exists() else {}
    for name, (url, _, _) in SOURCES.items():
        data = urllib.request.urlopen(url, timeout=60).read()
        payload = yaml.safe_load(data)['payload']
        if not isinstance(payload, list) or not payload: raise ValueError('Invalid payload')
        if name in previous and len(payload) < previous[name]['upstream_count'] * 0.5:
            raise ValueError(f'{name}: upstream shrank by more than half; review manually')
        kept, removed = filter_rules(name, payload)
        license_name = 'MetaCubeX-GPL-3.0.txt' if name == 'OtherAI' else 'blackmatrix7-GPL-2.0.txt'
        pending[name] = '# License: licenses/'+license_name+'; attribution retained in manifest.json\n# Generated by scripts/sync_sources.py\n# Source: '+url+'\n'+yaml.safe_dump({'payload':kept},allow_unicode=True,sort_keys=False)
        manifest[name] = {'source':url,'upstream_count':len(payload),'kept_count':len(kept),'removed':removed}
    # Publish only after all downloads parse successfully.
    for name, content in pending.items():
        (ROOT/'rules/filtered'/f'{name}.yaml').write_text(content)
    (ROOT/'rules/filtered/manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
    print('Refreshed', ', '.join(pending))

if __name__ == '__main__': main()
